routes/web.php
<?php

use App\Models\Obat;
use App\Models\User;
use App\Models\Kategori;
use App\Models\Supplier;
use App\Models\UserProfile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PengaturanController;
use App\Http\Controllers\SupplierController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan');
    Route::get('/penjualan/kasir', [PenjualanController::class, 'create'])->name('penjualan.kasir');
    Route::get('/penjualan/kasirmin/{id}', [PenjualanController::class, 'min'])->name('kasir.min');
    Route::get('/penjualan/kasirdel/{id}', [PenjualanController::class, 'del'])->name('kasir.del');
    Route::get('/pembelian', [PembelianController::class, 'index'])->name('pembelian');
    Route::get('/penjualan/bukti/{id}', [PenjualanController::class, 'bukti'])->name('penjualan.bukti');
    Route::post('penjualan/add', [PenjualanController::class, 'add'])->name('kasir.add');
    Route::post('penjualan/transaksi', [PenjualanController::class, 'transaksi'])->name('kasir.transaksi');
    Route::get('supplier', [SupplierController::class, 'index'])->name('supplier');
    Route::post(
        '/supplier/add',
        [SupplierController::class, 'store']
    )->name('supplier.add');
    Route::post(
        '/supplier/{supplier}/edit',
        [SupplierController::class, 'update']
    )->name('supplier.update');
    Route::get(
        '/supplier/{id?}/delete',
        [SupplierController::class, 'destroy']
    )->name('supplier.delete');
    Route::get('penjualan/reset', function () {
        session()->forget('kasir');
        return redirect(route('penjualan.kasir'));
    })->name('kasir.reset');
    Route::get('penjualan/add', function () {
        return redirect(route('penjualan.kasir'));
    })->name('kasir.add.redirect');
    Route::get('penjualan/transaksi', function () {
        return redirect(route('penjualan.kasir'));
    })->name('kasir.transaksi.redirect');
    Route::get(
        '/user',
        [UserController::class, 'index']
    )->name('user');
    Route::post(
        '/user/add',
        [UserController::class, 'store']
    )->name('user.add');
    Route::post(
        '/user/delete',
        [UserController::class, 'destroy']
    )->name('user.delete');
    Route::get(
        '/pengaturan',
        [PengaturanController::class, 'index']
    )->name('pengaturan');
    Route::get(
        '/obat',
        [ObatController::class, 'index']
    )->name('obat');
    Route::post(
        '/obat/add',
        [ObatController::class, 'store']
    )->name('obat.add');
    Route::post(
        '/obat/{obat}/edit',
        [ObatController::class, 'update']
    )->name('obat.update');
    Route::get(
        '/obat/{id?}/delete',
        [ObatController::class, 'destroy']
    )->name('obat.delete');
    Route::get(
        '/pengaturan/opname-edit',
        [PengaturanController::class, 'opname']
    )->name('pengaturan.opname');
    Route::get(
        '/pengaturan/obat-edit',
        [PengaturanController::class, 'obat']
    )->name('pengaturan.obat');
    Route::post(
        '/pengaturan/edit',
        [PengaturanController::class, 'update']
    )->name('pengaturan.edit');
    Route::get(
        '/kategori',
        [KategoriController::class, 'index']
    )->name('kategori');
    Route::post(
        '/kategori/add',
        [KategoriController::class, 'store']
    )->name('kategori.add');
    Route::get(
        '/kategori/{id?}/delete',
        [KategoriController::class, 'destroy']
    )->name('kategori.delete');
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard-app.blade.php
@extends('layouts.main')
@section('Content')
           <div class="row">

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-primary shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                Jumlah obat</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{$jumlah_obat}}</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="bi bi-capsule fa-2x text-gray-300 "></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-success shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                               Jumlah suplier </div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{$jumlah_supplier}}</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="bi bi-cart2 fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-info shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Pendapatan (monthly)</div>
                                            <div class="row no-gutters align-items-center">
                                                <div class="col-auto">
                                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                                                </div>
                                                <div class="col">
                                                    <div class="progress progress-sm mr-2">
                                                        <div class="progress-bar bg-info" role="progressbar"
                                                            style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                                            aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="bi bi-currency-dollar fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Pending Requests Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-warning shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                                Kadaluarsa</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="bi bi-capsule-pill fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
@endsection
@section('Model')
@endsection
@push('style')
    <style></style>
@endpush
@push('script')
    <script>
        async function test() {
            const response = await fetch('http://localhost:8000/test');
            console.log(await response.json());
        }
        test();
    </script>
    <!-- Bootstrap core JavaScript-->
    <script src={{ URL::asset('template/vendor/jquery/jquery.min.js') }}></script>
    <script src={{ URL::asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}></script>

    <!-- Core plugin JavaScript-->
    <script src={{ URL::asset('template/vendor/jquery-easing/jquery.easing.min.js') }}></script>

    <!-- Custom scripts for all pages-->
    <script src={{ URL::asset('template/js/sb-admin-2.min.js') }}></script>

    <!-- Page level plugins -->
    <script src={{ URL::asset('template/vendor/chart.js/Chart.min.js') }}></script>

    <!-- Page level custom scripts -->
    <script src={{ URL::asset('template/js/demo/chart-area-demo.js') }}></script>
    <script src={{ URL::asset('template/js/demo/chart-pie-demo.js') }}></script>
@endpush

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/detailpenjualan.blade.php
@extends('layouts.main')
@section('Content')
    <div class="container">
        <!-- DIISI DISINI -->
        @if (session()->has('status'))
            <div class="alert alert-success" role="alert">
                {{ session()->get('status') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger" role="alert">
                Ada Kesalahan Saat Menyimpan Obat..!! - (lihat Note Dibawah)
            </div>
        @endif
        @if (session()->has('success'))
            <div class="alert alert-success" role="alert">
                {{ session()->get('success') }}
            </div>
        @endif
        @if (session()->has('failed'))
            <div class="alert alert-danger" role="alert">
                {{ session()->get('failed') }}
            </div>
        @endif
        <!-- DataTales Example -->
        <div class="card shadow mb-3">
            <div class="card-header py-3">
                <h5 class="m-0 font-weight-bold text-primary">Data Penjualan - {{ $penjualan->id }}</h5>
            </div>

            <div class="card-body">
                <div class="mb-3">
                    <h5 style="text-align: right">Tanggal : {{ $penjualan->created_at }}</h5>
                    <h5 style="text-align: right; font-weight: bold; text-decoration: underline">
                        {{ $penjualan->user->name }}</h5>
                    <hr>
                    <h5>Costumer : {{ $penjualan->costumer }}</h5>
                </div>
                <!-- tables -->
                <div class="table-responsive">
                    <table class="table table-sm" id="dataTable" width="100%">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Obat</th>
                                <th scope="col">Jumlah</th>
                                <th scope="col">SubTotal</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($penjualan->detail_penjualan as $item)
                                <tr>
                                    <td scope="row">{{ $loop->iteration }}</td>
                                    <td>{{ $item->obat->nama }}</td>
                                    <td>{{ $item->jumlah }}</td>
                                    <td>Rp. {{ number_format($item->sub_total, 0, ',', '.') }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @if ($errors->any())
                        <div>Note: Error Saat Ingin Menambahkan/Mengedit Obat..<ol>
                                @foreach ($errors->all() as $error)
                                    <li class="text-danger">{{ $error }}</li>
                                @endforeach
                            </ol>
                        </div>
                    @endif
                    {{-- {{ $obat->links() }} --}}
                </div>
            </div>
            <div class="card-footer">
                <div class="mb-3 float-right">
                    <table style="font-size: 1.15rem; text-align: right">
                        <tr>
                            <td>Total Harga</td>
                            <td> : </td>
                            <td>
                                <h6 style="visibility: hidden">0</h6>
                            </td>
                            <td><strong>Rp. {{ number_format($penjualan->total_harga, 0, ',', '.') }}</strong> </td>
                        </tr>
                        <tr>
                            <td>Total Bayar</td>
                            <td> : </td>
                            <td>
                                <h6 style="visibility: hidden">0</h6>
                            </td>
                            <td><strong>Rp. {{ number_format($penjualan->total_bayar, 0, ',', '.') }}</strong>
                        </tr>
                        <tr>
                            <td>kembalian</td>
                            <td> : </td>
                            <td>
                                <h6 style="visibility: hidden">0</h6>
                            </td>
                            <td><strong>Rp. {{ number_format($penjualan->kembalian, 0, ',', '.') }}</strong>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('Model')
@endsection
@push('style')
    <style></style>
@endpush
@push('script')
    <script></script>
    <!-- Bootstrap core JavaScript-->
    <script src={{ URL::asset('template/vendor/jquery/jquery.min.js') }}></script>
    <script src={{ URL::asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}></script>

    <!-- Core plugin JavaScript-->
    <script src={{ URL::asset('template/vendor/jquery-easing/jquery.easing.min.js') }}></script>

    <!-- Custom scripts for all pages-->
    <script src={{ URL::asset('template/js/sb-admin-2.min.js') }}></script>

    <!-- Page level plugins -->
    <script src={{ URL::asset('template/vendor/chart.js/Chart.min.js') }}></script>

    <!-- Page level custom scripts -->
    <script src={{ URL::asset('template/js/demo/chart-area-demo.js') }}></script>
    <script src={{ URL::asset('template/js/demo/chart-pie-demo.js') }}></script>
@endpush

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index</title>
    @vite('resources/css/app.css')
</head>

<body>
    <h1 class="text-3xl font-bold underline">

    </h1>
</body>

</html>

resources/views/kasir.blade.php
@extends('layouts.main')
@section('Content')
    <div class="container">
        <!-- DIISI DISINI -->
        @if (session()->has('status'))
            <div class="alert alert-success" role="alert">
                {{ session()->get('status') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger" role="alert">
                Ada Kesalahan Saat Menyimpan Obat..!! - (lihat Note Dibawah)
            </div>
        @endif
        @if (session()->has('success'))
            <div class="alert alert-success" role="alert">
                {{ session()->get('success') }}
            </div>
        @endif
        @if (session()->has('failed'))
            <div class="alert alert-danger" role="alert">
                {{ session()->get('failed') }}
            </div>
        @endif
        <!-- DataTales Example -->
        <h3 class="text-center">KASIR - APOTEK</h3>
        <div class="card shadow mb-3">
            <div class="card-header py-3">
                <h5 class="m-0 font-weight-bold text-primary">Tambah Penjualan</h5>
            </div>
            <div class="card-body py-3">
                <form action="{{ route('kasir.add') }}" method="POST">
                    @csrf
                    <div class="row" style="align-content: center">
                        <div class="col-7 p-1">
                            <div><select class="form-select form-select-sm" id="obat" name="obat" required>
                                    <option disabled>Pilih Obat</option>
                                    @foreach ($obat as $i)
                                        <option value="{{ $i->kode }}">
                                            {{ $i->kode }} - {{ $i->nama }} I Stok:({{ $i->stok }})
                                        </option>
                                    @endforeach
                                </select></div>
                        </div>
                        <div class="col-2 p-1">
                            <div><input type="number" class="form-control form-control-sm" placeholder="Qty"
                                    name="jumlah"></div>
                        </div>
                        <div class="col-2 p-1">
                            <button style="width: 100%" type="submit" class="btn btn-success btn-sm">Tambah</button>
                        </div>
                        <div class="col-1 p-1">
                            <a style="width: 100%" href="{{ route('kasir.reset') }}"
                                onclick="return confirm('Yakin Ingin Mereset?')" class="btn btn-danger btn-sm">Reset</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card shadow mb-3">
            <div class="card-header py-3">
                <h5 class="m-0 font-weight-bold text-primary">Detail</h5>
            </div>
            <div class="card-body py-3">
                <div class="table-responsive">
                    <table class="table table-sm" id="dataTable" width="100%">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Obat</th>
                                <th scope="col">Harga</th>
                                <th scope="col">Jumlah</th>
                                <th scope="col">Sub Total</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                            @if (session()->get('kasir') != null)
                                @foreach (session()->get('kasir') as $item)
                                    <tr>
                                        <td scope="row">{{ $loop->iteration }}</td>
                                        <td>{{ $item['obat'][0]->nama }}</td>
                                        <td>{{ 'Rp. ' . number_format($item['obat'][0]->harga_jual, 0, ',', '.') }}</td>
                                        <td>{{ number_format($item['jumlah'], 0, ',', '.') }}</td>
                                        <td>{{ 'Rp. ' . number_format($item['obat'][0]->harga_jual * $item['jumlah'], 0, ',', '.') }}
                                        </td>
                                        <td style="vertical-align: middle">
                                            <div style="display: flex; gap:0.5rem; justify-content: start; width: 40px;">
                                                <a href="{{ route('kasir.min', $item['id']) }}" class="link-dark"
                                                    style="color: white !important"><span
                                                        class="badge text-bg-primary p-2">-</span></a>
                                                <span class="badge text-bg-danger p-2"><a
                                                        href="{{ route('kasir.del', $item['id']) }}" class="link-dark"
                                                        style="color: white !important">Delete</a></span>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                    @if ($errors->any())
                        <div>Note: Error Saat Ingin Menambahkan/Mengedit Obat..<ol>
                                @foreach ($errors->all() as $error)
                                    <li class="text-danger">{{ $error }}</li>
                                @endforeach
                            </ol>
                        </div>
                    @endif
                    {{-- {{ $obat->links() }} --}}
                </div>
            </div>
            <div class="card-footer py-3" x-data="transaksi">
                <form action="{{ route('kasir.transaksi') }}" method="POST">
                    @csrf
                    <h6 style="text-align: right" class="mx-4">GRANT TOTAL : <strong>Rp. <span x-text="grantTotal"></span>
                        </strong></h6>
                    <h6 style="text-align: right" class="mx-4">TOTAL KEMBALIAN : <strong>Rp. <span
                                x-text="(kembalian > 0) ? kembalian : 0"></span></strong></h6><br>
                    <div style="display: flex; gap:.65rem; justify-content: end;" class="mb-3">
                        <div style="flex-basis: 5%">
                            <button style="width: 100%" type="button" class="btn btn-primary btn-sm"
                                x-on:click="noCostumer ? (costumer = 'Unknown Constumer') : (costumer = '')">?</button>
                        </div>
                        <div style="flex-basis: 65%"><input class="form-control form-control-sm" type="text"
                                placeholder="Nama Costumer" x-model.text="costumer" name="costumer"></div>
                        <div style="flex-basis: 30%"><input class="form-control form-control-sm" type="text"
                                placeholder="Nominal Bayar" x-model.number="totalBayar" name="totalbayar"></div>
                    </div>
                    <div>
                        <button style="width: 100%" type="submit" class="btn btn-primary btn-sm"
                            :class="transaksi ? '' : 'disabled'">Transaksi</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('Model')
@endsection
@push('style')
    <style>
        .select2-container .select2-selection--single {
            height: 31px !important;
            border-color: #d1d3e2 !important;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush
@push('script')
    @vite('resources/js/app.js')
    <!-- Bootstrap core JavaScript-->
    <script src={{ URL::asset('template/vendor/jquery/jquery.min.js') }}></script>
    <script src={{ URL::asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}></script>

    <!-- Core plugin JavaScript-->
    <script src={{ URL::asset('template/vendor/jquery-easing/jquery.easing.min.js') }}></script>

    <!-- Custom scripts for all pages-->
    <script src={{ URL::asset('template/js/sb-admin-2.min.js') }}></script>
    {{-- 
    <!-- Page level plugins -->
    <script src={{ URL::asset('template/vendor/chart.js/Chart.min.js') }}></script>

    <!-- Page level custom scripts -->
    <script src={{ URL::asset('template/js/demo/chart-area-demo.js') }}></script>
    <script src={{ URL::asset('template/js/demo/chart-pie-demo.js') }}></script> --}}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#obat').select2({
                height: '31px',
            });
        });
        document.addEventListener('alpine:init', () => {
            Alpine.data('transaksi', () => ({
                grantTotal: {{ session()->get('total', 0) }},
                totalBayar: 0,
                costumer: '',
                get kembalian() {
                    return (this.totalBayar - this.grantTotal);
                },
                get transaksi() {
                    return (this.totalBayar - this.grantTotal > 0 && (this.costumer !== '') && (this
                        .grantTotal > 0));
                },
                get noCostumer() {
                    return (this.costumer === '');
                }
            }));
        })
    </script>
@endpush